### ISSUE TITLE
Calculation of base metric on changed scope

### ISSUE THREAD

**Issue by harry-m** [mort666/cvss_rating#1]
I'm seeing behaviour here that I don't understand and am not sure is right.

Where the scope is changed on a CVSS3 score, the gem takes the privilege score from `PRIVILEGE_REQUIRED_CHANGED` rather than `PRIVILEGE_REQUIRED`:

````
def pr
  if @sc == 'changed'
    pr = get_key('PRIVILEGE_REQUIRED_CHANGED', @pr) unless @pr.nil?
  else
    pr = get_key('PRIVILEGE_REQUIRED', @pr) unless @pr.nil?
  end
end

````

This doesn't align with my understanding of how this should work - and I'm getting scores for a given vector that differ from those the First.org calculator gives me. 

For example:

````
irb(main):003:0> p= Cvss3::Rating.new
=> #<Cvss3::Rating:0x00007fc58c0ac7c0 @ex=1.0, @rl=1.0, @rc=1.0, @cr=1.0, @ir=1.0, @ar=1.0, @mav=nil, @mac=nil, @mpr=nil, @mui=nil, @mc=nil, @mi=nil, @ma=nil>
irb(main):005:0> p.parse('AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H')
=> ["AV:N", "AC:L", "PR:H", "UI:N", "S:C", "C:H", "I:H", "A:H"]
irb(main):006:0> p.cvss_base_score
=> [7.9, "High"]
irb(main):007:0> 
````

cvss3_rating gives 7.9, whereas [first.org gives 9.1](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H).

**Comment by mort666** [comment]
Hmm.. I spotted an issue myself a little while back and didn't have the time to actually run it down, this could actually be it.. For some reason the lookup for the value isn't happening so PR gets set to nil and that is causing the score to not work out. 

Just investigating, further and will make a change shortly.

**Comment by mort666** [comment]
Pushed A fix GH and will push new gem shortly.
